### ISSUE TITLE
Just installed and had this erro

### ISSUE THREAD

**Issue by Alicture** [DonJayamanne/vscodeJupyter#114]
### Environment data
VS Code version:1.21.1 
Jupyter Extension version:
OS and version:OSX 10.13.3

### Logs
Output from ```Jupyter``` output panel
```
, ({"message": "Forbidden", "reason": null})
, ({"message": "Forbidden", "reason": null})
, ({"message": "Forbidden", "reason": null})
```
Output from ```Console window``` (Help->Developer Tools menu)
```
```

### Steps to reproduce:
-
-

**Comment by Alicture** [comment]
and i got this now: 
, (Error: connect ECONNREFUSED 127.0.0.1:80
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14))

**Comment by Mornielome** [comment]
Can confirm, same error.

**Comment by Alicture** [comment]
@Mornielome I have solved this problem by using python2.7

**Comment by PoulTur** [comment]
I got the same error when using hyphen in py filename. Otherwise error was gone.

**Comment by jamesnewsome** [comment]
Same problem, even tried to remove the hyphen in file name didnt work for me.

**Comment by PercyLau** [comment]
I have the same problem. Does anyone have any idea to locate the root ?

**Comment by openddd-com** [comment]
Same problem

**Comment by openddd-com** [comment]
Same problem

**Comment by QuantumZain** [comment]
Yes I got this too as well, exact errors occuring.
Before Yesteday, when I've installed Jupyter, the error apppeared but then somehow it got fixed and started working. Yesterday, I tried running jupyter again through vscode, and the error appeared , since then I've tried to fix every single potential problem I can think of, but non worked. **please** help if there is any solution to this issue.

_Note: running jupyter and connecting to python kernel seems to work fine using the command prompt, the issue is only when it is started through the Vscode jupyter extension (using Run cell)_

If additional information is needed, I will respond as soon as I can.
thanks.

**Comment by QuantumZain** [comment]
I was able to remove the error, atleast for my case. Apparently the password that I set for Jupyter seems to cause the problem, so I removed it, checked Vscode and it worked. Though I don't think this is a **_Fix_** as I want to use a password instead of tokens. It is either a problem within the extension or that I did a mistake while seting it up..

Incase you want to remove your password:

- go to Users\[UserName]\.jupyter\jupyter_notebook_config.json 

- Change password to password= ' '
Thanks alot

**Comment by jasonwheritage** [comment]
I have the same issue,
Run cell using #%% does not work
Run cell using select lines then right-click does not work

**Comment by youngdou** [comment]
I solve this problem by the steps bellow :
1. run `jupyter notebook --generate-config`
```bash
(tensorflow) F:\DataSet\experiment>jupyter notebook --generate-config
Writing default config to: C:\Users\young\.jupyter\jupyter_notebook_config.py
```

2.  then , open the file  showed above `C:\Users\young\.jupyter\jupyter_notebook_config.py`

3.  search `c.NotebookApp.password`  and uncomment this line , then set `c.NotebookApp.password = ''`

4. restart the vscode
