### ISSUE TITLE
Error when running cell

### ISSUE THREAD

**Issue by SheepDomination** [DonJayamanne/vscodeJupyter#124]
When attempting to run a cell; I get the following error;

>  (Error: connect ECONNREFUSED 127.0.0.1:80
> 	at Object.exports._errnoException (util.js:1050:11)
> 	at exports._exceptionWithHostPort (util.js:1073:20)
> 	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14))
> , ({"message": "Forbidden", "reason": null})

**Comment by NiranjanAgaram** [comment]
Did You solve the error?
If yes, please provide me the solution.
