### ISSUE TITLE
jupiter looks for a kernel from a conda env that has been removed

### ISSUE THREAD

**Issue by simone-codeluppi** [DonJayamanne/vscodeJupyter#134]
### Environment data
VS Code version: 1.27.2
Jupyter Extension version: 1.1.4
OS and version: osx 10.13.6 

### Logs
Output from ```Jupyter``` output panel
```
Starting Jupyter Notebook
jupyter notebook --no-browser --port=8888 --NotebookApp.allow_origin="*"
[I 16:24:00.259 NotebookApp] Serving notebooks from local directory: /Users/simcod/Code/pysmFISH_RoboFISHI
[I 16:24:00.259 NotebookApp] The Jupyter Notebook is running at:
[I 16:24:00.259 NotebookApp] http://localhost:8888/?token=d82afe85619cbaf1f2fad9ac34ab780da2fd5dbbf688f3e7
[I 16:24:00.259 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:24:00.261 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=d82afe85619cbaf1f2fad9ac34ab780da2fd5dbbf688f3e7
[E 16:24:02.466 NotebookApp] Failed to run command:
    ['/Users/simcod/anaconda3/envs/starfish_master/bin/python', '-m', 'ipykernel_launcher', '-f', '/Users/simcod/Library/Jupyter/runtime/kernel-7110e735-e3d3-4a34-bd1d-ded0b7d373e4.json']
        PATH='/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/bin:/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/bin:/Users/simcod/google-cloud-sdk/bin:/Users/simcod/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': None, 'start_new_session': True}
    
[E 16:24:02.468 NotebookApp] Uncaught exception POST /api/kernels?1538144642418 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/kernels?1538144642418', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 47, in post
        kernel_id = yield gen.maybe_future(km.start_kernel(kernel_name=model['name']))
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/simcod/anaconda3/envs/starfish_master/bin/python': '/Users/simcod/anaconda3/envs/starfish_master/bin/python'
[W 16:24:02.477 NotebookApp] Unhandled error
[E 16:24:02.478 NotebookApp] {
      "User-Agent": "node-XMLHttpRequest",
      "Accept": "*/*",
      "Content-Type": "application/json",
      "Authorization": "token d82afe85619cbaf1f2fad9ac34ab780da2fd5dbbf688f3e7",
      "Host": "localhost:8888",
      "Content-Length": "26",
      "Connection": "close"
    }
[E 16:24:02.478 NotebookApp] 500 POST /api/kernels?1538144642418 (127.0.0.1) 56.93ms referer=None

```
Output from ```Console window``` (Help->Developer Tools menu)
```
"message": "Unhandled error", "reason": null, "traceback": "Traceback (most recent call last):\n  File   \"/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site- 
 packages/tornado/web.py\", line 1592, in _execute\n    result = yield result\n  File  
 \"/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site- 
 packages/tornado/gen.py\", line 1133, in run\n    value = future.result()\n  File  
 \"/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site- packages/tornado/gen.py\", line 1141, in run\n    yielded = self.gen.throw(*exc_info)\n  File  
 \"/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site- 
 packages/notebook/services/kernels/handlers.py\", line 47, in post\n    kernel_id = yield  
 gen.maybe_future(km.start_kernel(kernel_name=model['name']))\n  File  
 \"/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/lib/python3.6/site- 
 packages/tornado/gen.py\", line 1133, in run\n    value = future.result()\n  File  
 \"/Users/simcod/anaconda3/env...  
t.onDidNotificationChange @ notificationsAlerts.ts:41  
```

### Actual behavior
cannot run a cell..... it looks to me that is looking for this `'/Users/simcod/anaconda3/envs/starfish_master/bin/python'` that has been removed
this is the correct env '/Users/simcod/anaconda3/envs/roboFISHI_pysmFISH_env/'
### Steps to reproduce:
-
-

**Comment by simone-codeluppi** [comment]
Hi
solved it. There were some ipykernels still installed in juptyter even if I had a new installation of anaconda.

Thanks
