### ISSUE TITLE
Activating extension 'donjayamanne.jupyter' failed: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by bedge** [DonJayamanne/vscodeJupyter#138]
### Environment data
VS Code version: Version 1.29.0-insider (1.29.0-insider)
Jupyter Extension version: 1.1.4
OS and version: OSX High Sierra 10.13.6 (17G65)

### Logs
Output from ```Jupyter``` output panel
```
```
Output from ```Console window``` (Help->Developer Tools menu)
```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3278 Activating extension 'donjayamanne.jupyter' failed: Cannot read property 'prototype' of undefined.
E._logMessageInConsole @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3278
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:280 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'prototype' of undefined
	at runInContext (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/json3/lib/json3.js:50:30)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/json3/lib/json3.js:869:5)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/json3/lib/json3.js:902:4)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/json3/lib/json3.js:904:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/socket.io-parser/index.js:7:12)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/socket.io-parser/index.js:406:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/socket.io-client/lib/index.js:7:14)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/socket.io-client/lib/index.js:111:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/socket.io/lib/index.js:9:14)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/node_modules/socket.io/lib/index.js:445:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/display/server.js:3:12)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/display/server.js:145:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/display/main.js:16:18)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/display/main.js:169:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/main.js:12:16)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/main.js:278:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:15:808)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/extension.js:4:16)
	at Object.<anonymous> (/Users/bedge/.vscode-insiders/extensions/donjayamanne.jupyter-1.1.4/out/src/extension.js:32:3)
	at Module.i._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:16:65)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:268)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:548)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/bedge/.vscode-insiders/extensions/ryu1kn.text-marker-1.9.0/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:31:146)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:627:58 (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:295:77)
```

### Actual behavior

Experiencing startup errors and problems in keymapping, python completion intellisense.

Don't know if it's actually related to this extension, but stack dumps are usually bad, so hopefully this will be of use to someone.

### Steps to reproduce:
- Start vscode

**Comment by DonJayamanne** [comment]
Does this work in the Stable version of VS Code.
If it does, then its most likely an upstream VS Code Insiders issue https://github.com/Microsoft/vscode/issues/60190

**Comment by DonJayamanne** [comment]
Closing as upstream issue https://github.com/Microsoft/vscode/issues/60168
