### ISSUE TITLE
command 'jupyter.startNotebook' not found

### ISSUE THREAD

**Issue by schuster-rainer** [DonJayamanne/vscodeJupyter#45]
### Environment data
VS Code version: 1.12.0
Jupyter Extension version: 1.1.2
OS and version: MacOS 10.11.6

### Logs
Output from ```Jupyter``` output panel
```
```
Output from ```Console window``` (Help->Developer Tools menu)
```
Overwriting extension <<.erb>> to now point to mime <<text/x-erb>>
(anonymous) @ mime.ts:59
extensionHost.ts:285[Extension Host] Looking for parseable documents...
extensionHost.ts:285[Extension Host] Found all parseable documents.
extensionHost.ts:285[Extension Host] Parsing documents and looking for CSS class definitions...
extensionHost.ts:285[Extension Host] Sumary:
extensionHost.ts:285[Extension Host] 48 parseable documents found
extensionHost.ts:285[Extension Host] 4457 CSS class definitions found
extensionHost.ts:285[Extension Host] 1090 unique CSS class definitions found
extensionHost.ts:285[Extension Host] 1 failed attempts to parse. List of the documents:
extensionHost.ts:285[Extension Host] /Users/rainer/project/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css

extensionHost.ts:285[Extension Host] Activating extension `donjayamanne.jupyter` failed: Cannot read property 'indexOf' of undefined.
d.logExtensionHostMessage @ extensionHost.ts:285
extensionHost.ts:285[Extension Host] Activating extension `donjayamanne.jupyter` failed:  Cannot read property 'indexOf' of undefined
d.logExtensionHostMessage @ extensionHost.ts:285
extensionHost.ts:285[Extension Host] Here is the error stack:  TypeError: Cannot read property 'indexOf' of undefined
    at getAbsolutePath (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/configSettings.js:57:20)
    at PythonSettings.initializeSettings (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/configSettings.js:30:27)
    at PythonSettings (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/configSettings.js:20:14)
    at Object.<anonymous> (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/configSettings.js:51:33)
    at Object.<anonymous> (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/configSettings.js:106:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Y.o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366384)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/procUtils.js:8:18)
    at Object.<anonymous> (/Users/rainer/.vscode/extensions/donjayamanne.jupyter-1.1.2/out/src/common/procUtils.js:359:3)
    at Module._compile (module.js:571:32)
mainThreadExtensionService.ts:111Activating extension `donjayamanne.jupyter` failed: Cannot read property 'indexOf' of undefined.
t.$localShowMessage @ mainThreadExtensionService.ts:111
messageService.ts:125command 'jupyter.startNotebook' not found
e.doShow @ messageService.ts:125
messageService.ts:125command 'jupyter.selectExistingNotebook' not found
e.doShow @ messageService.ts:125
2extensionHost.ts:285[Extension Host] TextEditor is closed/disposed
d.logExtensionHostMessage @ extensionHost.ts:285
2extensionHost.ts:285[Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:285
shell.ts:474Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at TagManager.isEnabled (/Users/rainer/.vscode/extensions/formulahendry.auto-rename-tag-0.0.11/out/src/tagManager.js:52:56)
    at TagManager.updatePairedTag (/Users/rainer/.vscode/extensions/formulahendry.auto-rename-tag-0.0.11/out/src/tagManager.js:63:19)
    at vscode.workspace.onDidChangeTextDocument.event (/Users/rainer/.vscode/extensions/formulahendry.auto-rename-tag-0.0.11/out/src/tagManager.js:13:18)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at t.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:298227)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:266430)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:154933)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:155610)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:474
2extensionHost.ts:285[Extension Host] TextEditor is closed/disposed
d.logExtensionHostMessage @ extensionHost.ts:285
4extensionHost.ts:285[Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:285
shell.ts:474Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at TagManager.isEnabled (/Users/rainer/.vscode/extensions/formulahendry.auto-rename-tag-0.0.11/out/src/tagManager.js:52:56)
    at TagManager.updatePairedTag (/Users/rainer/.vscode/extensions/formulahendry.auto-rename-tag-0.0.11/out/src/tagManager.js:63:19)
    at vscode.workspace.onDidChangeTextDocument.event (/Users/rainer/.vscode/extensions/formulahendry.auto-rename-tag-0.0.11/out/src/tagManager.js:13:18)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at t.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:298227)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:266430)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:154933)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:155610)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:474
messageService.ts:125command 'jupyter.startNotebook' not found
```

### Actual behavior
jupyter doesn't start. 
'command 'jupyter.startNotebook' not found'

### Expected  behavior
Jupyter starts.

### Steps to reproduce:
- CMD+Shift p
- Every jupyter command

**Comment by schuster-rainer** [comment]
The error occurs, when the python extension is installed and disabled

**Comment by DonJayamanne** [comment]
@schuster-rainer apologies for never getting back to you. I'm unable to replicate this issue. Please could you let me know if it still persists, and feel free to open the issue.
Once again, sorry for never getting back to you on this issue.

**Comment by macshaggy** [comment]
All of unsudden, with the latest update to 1.26.1. I can no longer start a jupyter notebook from vs code. This is what I'm getting.

![vscode_jupyter_error](https://user-images.githubusercontent.com/796886/44753025-d22c7c00-aaea-11e8-8203-c6e11605cd8d.PNG)
