### ISSUE TITLE
Unable to determine version of Jupyter, Error: spawn jupyter ENOENT

### ISSUE THREAD

**Issue by treymerkley** [DonJayamanne/vscodeJupyter#93]
### Environment data
VS Code version: 1.18.1
Jupyter Extension version: 4.3.0
OS and version: Linux Mint 64-bit, Anaconda as Python environment

### Logs
Output from ```Jupyter``` output panel
Unable to determine version of Jupyter, Error: spawn jupyter ENOENT
Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
Notebook not selected/started
Notebook not selected/started
``
```
Output from ```Console window``` (Help->Developer Tools menu)
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 [/home/trey/.vscode/extensions/ms-python.python-0.9.0]: Command `jupyter.runSelectionLine` appears multiple times in the `commands` section.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 [/home/trey/.vscode/extensions/ms-python.python-0.9.0]: Command `jupyter.execCurrentCell` appears multiple times in the `commands` section.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 [/home/trey/.vscode/extensions/ms-python.python-0.9.0]: Command `jupyter.execCurrentCellAndAdvance` appears multiple times in the `commands` section.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 [/home/trey/.vscode/extensions/ms-python.python-0.9.0]: Command `jupyter.gotToPreviousCell` appears multiple times in the `commands` section.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 [/home/trey/.vscode/extensions/ms-python.python-0.9.0]: Command `jupyter.gotToNextCell` appears multiple times in the `commands` section.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 Overwriting extension <<.html>> to now point to mime <<text/x-html>>
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 Overwriting extension <<.htm>> to now point to mime <<text/x-html>>
(anonymous) @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] Error: spawn jupyter ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:9
shell.ts:459 spawn jupyter ENOENT: Error: spawn jupyter ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
e.onUnexpectedError @ shell.ts:459
(anonymous) @ shell.ts:419
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:123 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:377
(anonymous) @ extensionHost.ts:202
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
shell.ts:459 Failed to detect Jupyter Notebook. Please use 'Select Jupyter Notebook' command
e.onUnexpectedError @ shell.ts:459
(anonymous) @ shell.ts:419
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
2messageService.ts:126 Notebook not selected/started
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:36
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

### Actual behavior
When I attempt to run a cell or block of code, I get the above error(s).

### Expected  behavior
Any given cell runs and returns an expected result.

### Steps to reproduce:
To set up Anaconda environment:
-https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-vsc
To start code:
-#%%
import matplotlib.pyplot as plt
from matplotlib import style

click run cell

**Comment by sjml** [comment]
I wonder if this is something similar to [this bug](https://github.com/Microsoft/vscode-python/issues/1695) that I had with the Python extension... I'm seeing the same error message, using virtualenv (not conda), but it looks like Jupyter is trying to initialize itself before the Python extension has had a chance to recognize that it's using a specific Python environment. 

If I look closely, it seems the error message pops **before** the interpreter appears in the status bar. Obviously GUI updates are a hard thing to trust the ordering of, but it could be a thread worth pulling on. If I start VS Code from a terminal where the environment is already set up pointing to the local virtualenv, Jupyter behaves as expected. 

Apologies if this is solving a different problem than yours, but this is one of the first results searching for that error message. :)

**Comment by billywade** [comment]
I think I saw that before, but I remember the issue being slightly different or the fix didn't work for me. 

Either way, I've since left both VSCode and Jupyter for Emacs and Org-Babel/EIN, so this issue can be closed if needed.

**Comment by ibigpapa** [comment]
I have this issue

**Comment by leandro-ss** [comment]
+1

**Comment by Lirunhua** [comment]
+1
